source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '8.1'

use_frameworks!

def common_pods
  pod 'CocoaLumberjack', :git => "https://github.com/anton-matosov/CocoaLumberjack.git", :branch => "master"

  pod "StylingKitThemes/blue/css", :path => "./themes"
  pod "StylingKit/Cloud/WithLogging", :path => "../"
end

target 'StylingKit_Example', :exclusive => true do
  common_pods
end

target 'StylingKit_Tests', :exclusive => true do
  common_pods

  pod 'Kiwi', :inhibit_warnings => true
  pod 'FBSnapshotTestCase', :inhibit_warnings => true
end
