platform :ios, '8.1'
use_frameworks!

def common_pods
  pod 'CocoaLumberjack', :git => "https://github.com/anton-matosov/CocoaLumberjack.git", :branch => "master"

  pod "StylingKitThemes/blue/css", :path => "./themes"
  pod "StylingKit/Cloud/WithLogging", :path => "../"
end

target 'StylingKit_Example' do
  common_pods
end

target 'StylingKit_Tests' do
  common_pods

  pod "ReactiveCocoa", "~> 2.5"
  pod 'Expecta', :inhibit_warnings => true
  pod 'Kiwi', :inhibit_warnings => true
end
