#!/bin/bash

set -e
set -x

if [ -z $(which brew) ] ;then
	echo "== Installing homebrew package manager"
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew_install()
{
    brew list $1 > /dev/null || brew install $1
    brew outdated $1 || brew upgrade $1
}

if [[ $TRAVIS != true ]]; then
	echo "== Updating homebrew database"
	brew update
fi

echo "== Updating tools"

which ruby
ruby --version

gem install cocoapods
pod --version

if [[ $TRAVIS != true ]]; then
	brew_install rbenv ruby-build

	RUBY_VERSION="2.2.4"

	# Add rbenv to bash so that it loads every time you open a terminal
	RBENV_CONF='if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi'
	if ! grep -xq "$RBENV_CONF" ~/.bash_profile; then
		echo "$RBENV_CONF" >> ~/.bash_profile
		source ~/.bash_profile
	fi

	# Install Ruby
	rbenv install "$RUBY_VERSION" --skip-existing
	rbenv global "$RUBY_VERSION" --skip-existing

	echo "== Updating cocoapods master repo"
	pod setup --silent
	echo "== Done"
fi

brew_install carthage


gem install fastlane
gem install match

gem install sass

