#!/bin/bash

set -e
set -x

if [ -z $(which brew) ] ;then
	echo "== Installing homebrew package manager"
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew_install()
{
    brew list $1 > /dev/null || brew install $1
    brew outdated $1 || brew upgrade $1
}

if [[ $TRAVIS != true ]]; then
	echo "== Updating homebrew database"
	brew update
fi

echo "== Updating tools"

which ruby
ruby --version

if [[ $TRAVIS != true ]]; then
	brew_install "homebrew/versions/ruby22" # must have for El Capitan
	brew switch ruby 2.2.4 # the latest version compatible with cocoapods 0.38.2 and 0.39.0 (latest to date)

	echo "Ruby version after update"
	which ruby
	ruby --version


	echo "== Updating cocoapods master repo"
	pod setup --silent
	echo "== Done"
fi

brew_install carthage

gem install cocoapods
	
gem install fastlane
gem install match

gem install sass

