#! /bin/sh

set -e

open -b com.apple.iphonesimulator #start simulator in advance as xcodebuild sometimes fails to do so
set -o pipefail && xcodebuild clean build -workspace "$workspace" -scheme "$scheme" -destination "$destination" ONLY_ACTIVE_ARCH=NO | xcpretty
set -o pipefail && xcodebuild test -workspace "$workspace" -scheme "$scheme" -destination "$destination" | xcpretty
carthage build --no-skip-current
pod lib lint



